default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: daisyui-css
        name: build style.css
        entry: pnpm run build:css
        language: system
        files: ^(src/gtfs_zone_timetable_sites/templates/.*\.(html|css)|package\.json)$
        exclude: ^src/gtfs_zone_timetable_sites/templates/style\.css$
        pass_filenames: false
